name: Criar imagem docker ambiente producao

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t stvnreis/backend-atividade . && docker push stvnreis/backend-atividade:latest
