name: Deploy on render

on: 
  pull_request: 
    branches: ["master"]
  push: 
    branches: ["master"]

jobs: 

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl ${{ secrets.RENDER_HOOK_URL }}
      
