name: Deploy on render

on:
  workflow_run:
    workflows: ["Release Version"]
    types:
      - completed

jobs: 

  deploy:
    uses: ubuntu-latest
    steps:
      - run: curl ${{ secrets.RENDER_HOOK_URL }}