name: Deploy on render

on: 
  pull_request: 
    branches: ["master"]
  push: 
    branches: ["master"]

jobs: 

  deploy:
    uses: kamilchodola/wait-for-workflow-action@1.1.0
    with:
      GITHUB_TOKEN: ${{ github.token }}
      workflow_id: ./.github/workflows/build-docker-image-latest
      repo_name: 'health-app-backend-atividade'
      org_name: 'Rama-Developments'
    steps:
      - run: curl ${{ secrets.RENDER_HOOK_URL }}